apiVersion: v1
kind: ConfigMap
metadata:
  name: frappe-settings
  namespace: frappe
data:
  DB_HOST: mariadb
  DB_PORT: "3306"
  REDIS_CACHE: redis://redis:6379/0
  REDIS_QUEUE: redis://redis:6379/1
  REDIS_SOCKETIO: redis://redis:6379/2
  SITE_NAME: site1.local

